#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/sph_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmin_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/rmax_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmn_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/tmmx_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2020.nc 
