---
title: "A Summary of the models used to predict vegetation cover by functional group from climate, weather, and soils information"
format:
  html:
    toc: false
    number-sections: true
    colorlinks: true
---
# Calculate predictor variables 

```{=html}
<table style="border: none;border-collapse: collapse;width: 812px;" class="fr-table-selection-hover">
    <tbody>
        <tr>
            <td style="width: 76pt;border: 1pt solid windowtext;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;'>Equation Name</span></strong></p>
            </td>
            <td style="width: 85.5pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;'>Predictor</span></strong></p>
            </td>
            <td style="width: 49.2pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;'>units</span></strong></p>
            </td>
            <td style="width: 128.6pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;'>Scaling&nbsp;in cover models</span></strong></p>
            </td>
            <td style="width: 269.75pt;border-top: 1pt solid windowtext;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-image: initial;border-left: none;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><strong><span style='font-family:"Calibri",sans-serif;'>description</span></strong></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Tmean_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean annual temperature &ndash; mean across previous 30 years</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Degrees C.&nbsp;</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(Tmean_CLIM &ndash; 10.275203571)/</span><span style='font-size:13px;font-family:"Calibri",sans-serif;'>4.912309147</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years [mean across year(monthly mean temps.)]</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>precipTempCorr_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Precipitation Temperature correlation &ndash; mean across previous 30 years</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>correlation</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precipTempCorr_CLIM - -0.120988193) / 0.410662268</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years[correlation(each month&rsquo;s tmax, each month&rsquo;s tmin)]</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Isothermality_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Isothermality &ndash; mean across previous 30 years</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>unitless</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(isothermality_CLIM - 38.120111845) / 5.019479015</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;color:black;background:white;'>&nbsp;Mean across 30 years[(Mean of monthly (max temp - min temp))</span><span style='font-family:"Calibri",sans-serif;'>/(max temp. of warmest month &ndash; min. temp of coldest month) x 100]</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>annWatDef_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Annual water deficit &ndash; mean across previous 30 years</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>mm of water/</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>degrees C</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(annWatDef_CLIM - 99.631248729) / 85.941823498</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years[ sum across year(monthly mean*2 &ndash; monthly total precip)] &nbsp;*Note: only sum monthly water deficit values that are &gt;0</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>precip_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Total annual precipitation &ndash; mean across previous 30 years&nbsp;</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>mm</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precip_CLIM - 613.900118155) / 502.187690606</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years(annual total precip)</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>precipSeasonality_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Precipitation seasonality &ndash; mean across previous 30 years</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>mm</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precipSeasonality_CLIM - 0.923249309) / 0.245954382</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years (coefficient of variation of monthly total precip within a year)</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>precipDry_CLIM</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Precipitation of the driest month &ndash; mean across previous 30 years&nbsp;</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>mm</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precipDry_CLIM - 5.000260635) / 8.205443958</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean across 30 years (total precip of the driest month in the year)</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>annWetDegDays_CLIM</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Annual wet degree days &ndash; mean across previous 30 years</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Degree days</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(annWetDegDays_CLIM - 1762.977520092) / 1160.20756048</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Mean of annual wet degree days across the previous 30 years&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>twarm_CLIM</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Temp. of the warmest month &ndash; mean across previous 30 years</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Deg. C</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>n/a</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Maximum temperature of the warmest month in a year, averaged across previous 30 years&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>tcold_CLIM</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Temp. of the coldest &nbsp; &nbsp; month &ndash; mean across previous 30 years</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Deg. C</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>n/a</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Minimum temperature of the warmest month in a year, averaged across previous 30 years&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>precipWet_CLIM</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Precip. of the wettest month &ndash; mean across previous 30 years</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>mm</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>n/a</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Precip in mm of the wettest month in a year, averaged across previous 30 years&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>soilDepth</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>soilDepth</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>cm</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>n/a</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Depth of soil in the grid cell in cm&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>precipSeasonality_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Precip. Seasonality &ndash; anomaly of mean across previous 3 years relative to the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precipSeasonality_WEATH - -0.025697534) / 0.132964252</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(30 year mean of precip seasonality &ndash;3 year mean of precip seasonality)/30 year mean of precip seasonality</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>precip_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Precip. - anomaly of mean across previous 3 years relative to the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precip_WEATH - 0.030312573) / 0.168767355</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(30 year mean of precip &ndash;3 year mean of precip)/30 year mean of precip</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>annWetDegDays_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Annual wet degree days - anomaly of mean across previous 3 years relative to the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(annWetDegDays_WEATH - 0.02989113) / 0.243425185</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(30 year mean of annual wet degree days &ndash;3 year mean of annual wet degree days)/30 year mean of annual wet degree days</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>annWatDef_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Annual water deficit - anomaly of mean across previous 3 years relative to the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(annWatDef_WEATH --0.119596687) / 0.424434636</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(30 year mean of annual water deficit &ndash;3 year mean of annual water deficit)/30 year mean of annual water deficit</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;height: 128.15pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>isothermality_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;height: 128.15pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>Isothermality - anomaly of mean across previous 3 years relative to the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;height: 128.15pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Absolute difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;height: 128.15pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(isothermality_WEATH - 0.538807833) / 1.422356333</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;height: 128.15pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>30 year mean of isothermality &ndash; 3 year mean of isothermality</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'>annWetDegDays_WEATH</p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'>Annual wet degree days &ndash; anomaly of mean across previous 3 years relative to &nbsp;the 30 year mean</p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(annWetDegDays_WEATH - 0.02989113) / 0.243425185</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(30 year mean of annual wet degree days &ndash;3 year mean of annual wet degree days)/30 year mean of annual wet degree days</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>precipTempCorr_WEATH</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Precipitation Temperature correlation &ndash; anomaly of mean across previous 3 years relative to the 30 year mean</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Absolute difference</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(precipTempCorr_WEATH - 0.012171065) / 0.139613922</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>30 year mean of precipTempCorr &ndash; 3 year mean of precipTempCorr</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>sand</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% Sand across the soil profile</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>%</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(sand - 47.706485501) / 16.730875594</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Average % of sand across the soil profile, weighted by the width of each soil layer</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>coarse</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% Coarse fragments across the soil profile</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>%</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(coarse - 12.799273363) / 11.332548324</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Average % of coarse fragments across the soil profile, weighted by the width of each soil layer</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>AWHC</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Total soil available water holding capacity</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>&nbsp;</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(AWHC - 13.671423701) / 5.155757156</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>Calculated via following code: soils &lt;- rSOILWAT2::swSoils_Layers(rSOILWAT2::sw_exampleData)</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>p &lt;- rSOILWAT2::ptf_estimate( sand = soils[, sand_frac], &nbsp; &nbsp;clay = soils[, clay_frac], fcoarse = soils[, gravel_content], &nbsp; &nbsp;swrc_name = Campbell1974, &nbsp; &nbsp;ptf_name = Cosby1984)</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>tmp &lt;- rSOILWAT2::swrc_swp_to_vwc( c(-1.5, -0.033), &nbsp; &nbsp;fcoarse = soils[, gravel_content], swrc = list(name = Campbell1974, swrcp = p) )</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>&nbsp;</span></p>
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>awc &lt;- diff(c(0, soils[, depth_cm])) * as.vector(diff(tmp))</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>clay</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% Clay in the soil surface</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>%</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(clay - 18.489433548) / 9.078669938</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% of clay in the first 3 cm of the soil profile</span></p>
            </td>
        </tr>
        <tr>
            <td style="width: 76pt;border-right: 1pt solid windowtext;border-bottom: 1pt solid windowtext;border-left: 1pt solid windowtext;border-image: initial;border-top: none;padding: 0in;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>carbon</span></p>
            </td>
            <td style="width: 85.5pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% organic matter in the soil surface</span></p>
            </td>
            <td style="width: 49.2pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>%</span></p>
            </td>
            <td style="width: 128.6pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>(carbon - 3.681945502) / 6.405262851</span></p>
            </td>
            <td style="width: 269.75pt;border-top: none;border-left: none;border-bottom: 1pt solid windowtext;border-right: 1pt solid windowtext;padding: 0in 5.4pt;vertical-align: top;">
                <p style='margin-top:0in;margin-right:0in;margin-bottom:0in;margin-left:0in;line-height:normal;font-size:16px;font-family:"Aptos",sans-serif;'><span style='font-family:"Calibri",sans-serif;'>% of organic matter in the first 3 cm of the soil profile</span></p>
            </td>
        </tr>
    </tbody>
</table>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;line-height:115%;font-size:16px;font-family:"Aptos",sans-serif;'>&nbsp;</p>
```
 
# Predict 'raw' model outputs from climate, weather, and soils data
\*Note that for all of these models, the input variables are un-scaled. Centering and scaling, when applied, is included in the equation. There is no centering or scaling of variables in the ecoregion classificaiton model, but all other models include centering and scaling. The centering and scaling factors are included in the table above for reference. 

## Ecoregion classification model
$$
\begin{array}{cl}
P(forest) \sim  &1/ (1 + exp(-( 9.872597456 + -0.299906791*twarm\_CLIM +  0.245551132*tcold\_CLIM + \\
&0.010607279*precipWet\_CLIM + -0.062058523*annWatDef\_CLIM +\\
&-2.786336969*PrecipTempCorr\_CLIM +  0.054028905*isothermality\_CLIM +\\
&-0.007599899*soilDepth +  0.033478424*sand +  0.031037682*coarse +  0.272601351*carbon)))
&\end{array}
$$
AKA: 
P(forest) ~ 1/(1 + exp(-( 9.872597456 + -0.299906791\*twarm_CLIM +  0.245551132\*tcold_CLIM + 0.010607279\*precipWet_CLIM + -0.062058523\*annWatDef_CLIM + -2.786336969\*PrecipTempCorr_CLIM +  0.054028905\*isothermality_CLIM + -0.007599899\*soilDepth +  0.033478424\*sand +  0.031037682\*coarse +  0.272601351\*carbon)))

## "Level 1" functional group cover models

### Total Herbaceous Cover -- non-forest: 

$$
\begin{array}{cl}
&TotalHerbaceousCover\sim exp\big\{ 3.276248186 + 
0.333755104*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}  + 
0.000988410*\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}  + \\
&-0.093566592*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} + 
-0.401713218*\frac{(annWatDef\_CLIM- 99.631248729)}{85.941823498} + 
-0.101054822*\frac{(sand - 47.706485501)}{16.730875594} + \\
&-0.059075423*\frac{(coarse - 12.799273363)}{11.332548324} + 
0.097488751*\frac{(AWHC - 13.671423701)}{5.155757156} + \\
&-0.011392877*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}  +  
0.035960786*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636} + \\
&-0.217970279*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}\right)  ^2 +  
0.367790702*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + \\
&-0.031527015*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right)^2 +  
-0.001997141*\left(\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}\right) ^2 + \\
&-0.022758623*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right)^2 + 
0.014352225*\left(\frac{(sand - 47.706485501)}{16.730875594}\right)^2 + \\
&0.025503657*\left(\frac{(coarse - 12.799273363)}{11.332548324}\right)^2 +  
0.062557753*\left(\frac{(carbon - 3.681945502)}{6.405262851}\right)^2 + 
-0.048139022*\left(\frac{(AWHC - 13.671423701)}{5.155757156}\right)^2 +  \\
&0.002192693*\left(\frac{(annWatDef\_CLIM- 99.631248729)}{85.941823498}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) +  
0.014972237*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)  + \\ 
&-0.051575876*\left(\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}*\frac{(precip\_CLIM- 613.900118155)}{502.187690606}\right) +   
0.038675358*\left(\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)  + \\ 
&-0.009761302*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)  +  
0.289340507*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(precip\_CLIM- 613.900118155)}{502.187690606}\right) +  \\
&0.078632789*\left(\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) +  
0.132202861*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&-0.009488915*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) + 
0.063991677*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) + \\
&0.020965402*\left(\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)  + 
0.237331817*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\ 
&0.009654127*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}\right)  +  0.011241877*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}*\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}\right)  + \\
&-0.185452900*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) +  \\
&0.042165264*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(AWHC - 13.671423701)}{5.155757156}\right) + 
-0.014331054*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(coarse - 12.799273363)}{11.332548324}\right) \big\} - 2
\end{array}
$$

AKA: TotalHerbaceousCover~ exp( 3.276248186 + 0.333755104\*((tmean_CLIM- 10.275203571) / 4.912309147) +  0.000988410\*((precipSeasonality_CLIM - 0.923249309) / 0.245954382) + -0.093566592\*((isothermality_CLIM- 38.120111845) / 5.019479015) + -0.401713218\*((annWatDef_CLIM - 99.631248729) / 85.941823498) + -0.101054822\*((sand - 47.706485501) / 16.730875594) + -0.059075423\*((coarse - 12.799273363) / 11.332548324) +  0.097488751\*((AWHC - 13.671423701) / 5.155757156) +  0.013584831\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922) + -0.011392877\*((isothermality_WEATH - 0.538807833) / 1.422356333)  +  0.035960786\*((annWatDef_WEATH - -0.119596687) / 0.424434636)  + -0.217970279\*I(((precip_CLIM - 613.900118155) / 502.187690606)^2) +  0.367790702\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) + -0.031527015\*I(((isothermality_CLIM- 38.120111845) / 5.019479015)^2) + -0.001997141\*I(((precipSeasonality_WEATH - -0.025697534) / 0.132964252) ^2) + -0.022758623\*I(((precipTempCorr_WEATH - 0.012171065) / 0.139613922)^2) + 0.014352225\*I(((sand - 47.706485501) / 16.730875594)^2) +  0.025503657\*I(((coarse - 12.799273363) / 11.332548324)^2) +  0.062557753\*I(((carbon - 3.681945502) / 6.405262851)^2) + -0.048139022\*I(((AWHC - 13.671423701) / 5.155757156)^2) +  0.002192693\*(((annWatDef_CLIM - 99.631248729) / 85.941823498)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) +  0.014972237\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((annWatDef_WEATH - -0.119596687) / 0.424434636))  + -0.051575876\*(((annWatDef_WEATH - -0.119596687) / 0.424434636)\*((precip_CLIM - 613.900118155) / 502.187690606)) +  0.038675358\*(((precipSeasonality_CLIM - 0.923249309) / 0.245954382)\*((annWatDef_WEATH - -0.119596687) / 0.424434636))  + -0.009761302\*(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)\*((annWatDef_WEATH - -0.119596687) / 0.424434636))  +  0.289340507\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((precip_CLIM - 613.900118155) / 502.187690606)) +  0.078632789\*(((precipSeasonality_CLIM - 0.923249309) / 0.245954382)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) + 0.132202861\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.009488915\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) +  0.063991677\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) +  0.020965402\*(((precipSeasonality_CLIM - 0.923249309) / 0.245954382)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  +  0.237331817\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + 0.009654127\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((precipSeasonality_WEATH - -0.025697534) / 0.132964252))  +  0.011241877\*(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)\*((precipSeasonality_WEATH - -0.025697534) / 0.132964252))  + -0.185452900\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) +  0.042165264\*(((sand - 47.706485501) / 16.730875594)\*((AWHC - 13.671423701) / 5.155757156)) + -0.014331054\*(((sand - 47.706485501) / 16.730875594)\*((coarse - 12.799273363) / 11.332548324))) - 2

### Total Herbaceous Cover -- forest

$$
\begin{array}{cl}
&TotalHerbaceousCover \sim exp\big\{3.191837402 + 
-0.122792350*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} +
0.116138373*\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958} + \\ 
&0.073364801*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268} + 
-0.223502453*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} +  
0.059416398*\frac{(clay - 18.489433548)}{9.078669938} + \\
&-0.143976298*\frac{(sand - 47.706485501)}{16.730875594} +  
0.093798717*\frac{(AWHC - 13.671423701)}{5.155757156} + \\ 
&-0.082685833*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}  + 
-0.026084114*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}  +  
0.067376300*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + \\ 
&0.025575815*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right)^2 +  
0.010298554*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)^2 + 
-0.001326385*\left(\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)^2 + \\
&0.075308377*\left(\frac{(sand - 47.706485501)}{16.730875594}\right)^2 +  
0.073306773*\left(\frac{(AWHC - 13.671423701)}{5.155757156}\right)^2 +  \\
&0.019965778*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)  +  
-0.016757681*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}\right)  + \\
&-0.010148936*\left(\frac{(annWatDef\_WEATH - -0.119596687)}{0.424434636}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) +   
0.092170440*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) +  \\
&0.016099673*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)  + 
0.019360302*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}*\frac{(precip\_WEATH - 0.030312573)}{0.168767355}\right)  + \\
&-0.007884072*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)  +  
-0.006048882*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) + \\
&-0.070468595*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) + 
-0.013811905*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) + \\
&0.030103657*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(precip\_WEATH - 0.030312573)}{0.168767355}\right)  +
-0.001131342*\left(\frac{(precip\_WEATH - 0.030312573)}{0.168767355}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) + \\
&0.029138569*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147})*\frac{(precip\_WEATH - 0.030312573)}{0.168767355}\right)  +  
-0.081971171*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&-0.015253376*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) + \\
& -0.039321175*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) +   
0.042655226*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) + \\
&0.013823818*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right) + 
-0.020024507*\left(\frac{(AWHC - 13.671423701)}{5.155757156}*\frac{(carbon - 3.681945502)}{6.405262851}\right) +  \\
&0.078265961*\left(\frac{(clay - 18.489433548)}{9.078669938})*\frac{(AWHC - 13.671423701)}{5.155757156}\right) +  \\
&0.081708191*\left(\frac{(AWHC - 13.671423701)}{5.155757156}*\frac{(coarse - 12.799273363)}{11.332548324}\right) +  
0.185762180*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(AWHC - 13.671423701)}{5.155757156}\right) + \\
&-0.025554099*\left(\frac{(carbon - 3.681945502)}{6.405262851}*\frac{(coarse - 12.799273363)}{11.332548324}\right) +  
-0.038284034*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(carbon - 3.681945502)}{6.405262851}\right)\big\} - 2
\end{array}
$$

AKA: 
TotalHerbaceousCover~ exp( 3.191837402 + -0.122792350\*((precip_CLIM - 613.900118155) / 502.187690606) +  0.116138373\*((precipDry_CLIM - 5.000260635) / 8.205443958) +  0.073364801\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268) + -0.223502453\*((isothermality_CLIM- 38.120111845) / 5.019479015) + 0.059416398\*((clay - 18.489433548) / 9.078669938) + -0.143976298\*((sand - 47.706485501) / 16.730875594) +  0.093798717\*((AWHC - 13.671423701) / 5.155757156) + -0.082685833\*((isothermality_WEATH - 0.538807833) / 1.422356333)  + -0.026084114\*((annWatDef_WEATH - -0.119596687) / 0.424434636)  +  0.067376300\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) +  0.025575815\*I(((isothermality_CLIM- 38.120111845) / 5.019479015)^2) +  0.010298554\*I(((isothermality_WEATH - 0.538807833) / 1.422356333) ^2) + -0.001326385\*I(((annWatDef_WEATH - -0.119596687) / 0.424434636) ^2) +  0.075308377\*I(((sand - 47.706485501) / 16.730875594)^2) +  0.073306773\*I(((AWHC - 13.671423701) / 5.155757156)^2) + 0.019965778\*(((isothermality_WEATH - 0.538807833) / 1.422356333)\*((annWatDef_WEATH - -0.119596687) / 0.424434636))  + -0.016757681\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((annWatDef_WEATH - -0.119596687) / 0.424434636))  + -0.010148936\*(((annWatDef_WEATH - -0.119596687) / 0.424434636) \*((tmean_CLIM- 10.275203571) / 4.912309147)) +  0.092170440\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) +  0.016099673\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  +  0.019360302\*(((isothermality_WEATH - 0.538807833) / 1.422356333) \*((precip_WEATH - 0.030312573) / 0.168767355)) + -0.007884072\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  + -0.006048882\*(((isothermality_WEATH - 0.538807833) / 1.422356333) \*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) + -0.070468595\*(((isothermality_WEATH - 0.538807833) / 1.422356333) \*((tmean_CLIM- 10.275203571) / 4.912309147)) + -0.013811905\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) +  0.030103657\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((precip_WEATH - 0.030312573) / 0.168767355))  + -0.001131342\*(((precip_WEATH - 0.030312573) / 0.168767355) \*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) +  0.029138569\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precip_WEATH - 0.030312573) / 0.168767355))  +-0.081971171\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.015253376\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((tmean_CLIM- 10.275203571) / 4.912309147)) + -0.039321175\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) +  0.042655226\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((tmean_CLIM- 10.275203571) / 4.912309147)) +  0.013823818\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) + -0.020024507\*(((AWHC - 13.671423701) / 5.155757156)\*((carbon - 3.681945502) / 6.405262851)) +  0.078265961\*(((clay - 18.489433548) / 9.078669938)\*((AWHC - 13.671423701) / 5.155757156)) +  0.081708191\*(((AWHC - 13.671423701) / 5.155757156)\*((coarse - 12.799273363) / 11.332548324)) + 0.185762180\*(((sand - 47.706485501) / 16.730875594)\*((AWHC - 13.671423701) / 5.155757156)) + -0.025554099\*(((carbon - 3.681945502) / 6.405262851)\*((coarse - 12.799273363) / 11.332548324)) + -0.038284034\*(((sand - 47.706485501) / 16.730875594)\*((carbon - 3.681945502) / 6.405262851))) - 2

### Total Tree Cover -- non-forest

$$
\begin{array}{cl}
 &TotalTreeCover\sim exp\big\{ 2.58245786 +  
1.14190425*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + 
-0.15075425*\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382} + \\ 
&0.03572512*\frac{(annWatDef\_CLIM- 99.631248729)}{85.941823498} + 
-0.07413619*\frac{(sand - 47.706485501)}{16.730875594} + 
-0.31894087*\frac{(AWHC - 13.671423701)}{5.155757156}\big\} - 2
\end{array}
$$

AKA: 
TotalTreeCover~ exp( 2.58245786 +  1.14190425\*((precip_CLIM - 613.900118155) / 502.187690606) + -0.15075425\*((precipSeasonality_CLIM - 0.923249309) / 0.245954382) +  0.03572512\*((annWatDef_CLIM - 99.631248729) / 85.941823498) + -0.07413619\*((sand - 47.706485501) / 16.730875594) + -0.31894087\*((AWHC - 13.671423701) / 5.155757156)) - 2

### Total Tree Cover -- forest

$$
\begin{array}{cl}
TotalTreeCover\sim &exp\big\{3.28887888 +  
0.10058372*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} +  
0.07165316*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + \\
&0.12712928*\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958} +  
0.03173495*\frac{(carbon - 3.681945502)}{6.405262851} +  
0.06648011*\frac{(AWHC - 13.671423701)}{5.155757156} + \\ 
&-0.17846554*\frac{(precip\_WEATH - 0.030312573)}{0.168767355} + 
-0.02914362*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)^2 + 
-0.04902481*\left(\frac{(clay - 18.489433548)}{9.078669938}\right)^2 +  \\
&0.11841332*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)  +  0.11243677*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&0.02314517*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}\right) +  
-0.16107089*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&-0.03108354*\left(\frac{(carbon - 3.681945502)}{6.405262851}*\frac{(clay - 18.489433548)}{9.078669938}\right) + 
0.04845871*\left(\frac{(carbon - 3.681945502)}{6.405262851}*\frac{(coarse - 12.799273363)}{11.332548324}\right)\big\} - 2
\end{array}
$$

AKA: 
TotalTreeCover~ exp( 3.28887888 +  0.10058372\*((tmean_CLIM- 10.275203571) / 4.912309147) +  0.07165316\*((precip_CLIM - 613.900118155) / 502.187690606) +  0.12712928\*((precipDry_CLIM - 5.000260635) / 8.205443958) +  0.03173495\*((carbon - 3.681945502) / 6.405262851) + 0.06648011\*((AWHC - 13.671423701) / 5.155757156) + -0.17846554\*((precip_WEATH - 0.030312573) / 0.168767355)  + -0.02914362\*I(((isothermality_WEATH - 0.538807833) / 1.422356333) ^2) + -0.04902481\*I(((clay - 18.489433548) / 9.078669938)^2) +  0.11841332\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  +  0.11243677\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + 0.02314517\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipDry_CLIM - 5.000260635) / 8.205443958)) + -0.16107089\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.03108354\*(((carbon - 3.681945502) / 6.405262851)\*((clay - 18.489433548) / 9.078669938)) +  0.04845871\*(((carbon - 3.681945502) / 6.405262851)\*((coarse - 12.799273363) / 11.332548324))) - 2

### shrub cover -- CONUS-wide

$$
\begin{array}{cl}
&ShrubCover\sim exp\big\{2.939339967 +  
0.145466528*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + 
-0.106416302*\frac{(precipSeasonality\_CLIM- 0.923249309)}{0.245954382} + \\
&-0.216540564*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268} +  
0.091558229*\frac{(sand - 47.706485501)}{16.730875594} +  
0.007762789*\frac{(coarse - 12.799273363)}{11.332548324} + \\
&-0.083296458*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + 
-0.056281606*\left(\frac{(sand - 47.706485501)}{16.730875594}\right)^2 + 
-0.006510544*\left(\frac{(AWHC - 13.671423701)}{5.155757156}\right)^2 +  \\
&0.048231968*\left(\frac{(annWetDegDays\_CLIM - 1762.977520092)}{1160.20756048}*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)  +  -0.030802083*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333})*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) + \\
&0.117940292*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) +  0.037905068*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}\right)  +  \\
&0.045575111*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right)\big\} - 2
\end{array}
$$

AKA:
ShrubCover ~ exp( 2.939339967 +  0.145466528\*((precip_CLIM - 613.900118155) / 502.187690606) +-0.106416302\*((precipSeasonality_CLIM - 0.923249309) / 0.245954382) +-0.216540564\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268) + 0.091558229\*((sand - 47.706485501) / 16.730875594) + 0.007762789\*((coarse - 12.799273363) / 11.332548324) + -0.083296458\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) + -0.056281606\*I(((sand - 47.706485501) / 16.730875594)^2) +-0.006510544\*I(((AWHC - 13.671423701) / 5.155757156)^2) +  0.048231968\*(((annWetDegDays_CLIM - 1762.977520092) / 1160.20756048)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  + -0.030802083\*(((isothermality_WEATH - 0.538807833) / 1.422356333) \*((isothermality_CLIM- 38.120111845) / 5.019479015)) +  0.117940292\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((tmean_CLIM- 10.275203571) / 4.912309147)) +0.037905068\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((precipSeasonality_WEATH - -0.025697534) / 0.132964252))  +  0.045575111\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((tmean_CLIM- 10.275203571) / 4.912309147))) - 2

### bare ground cover -- CONUS-wide

$$
\begin{array}{cl}
&BareGroundCover \sim exp\big\{2.746284299 +  
0.262457983*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} + 
0.087718972*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} + \\ 
&-0.715375616*\frac{(annWetDegDays\_CLIM - 1762.977520092)}{1160.20756048} + 
-0.267155829*\frac{(coarse - 12.799273363)}{11.332548324} + 
-0.064084039*\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}  + \\
&0.037782133*\frac{(annWetDegDays\_WEATH - 0.02989113)}{0.243425185} + 
-0.079708661*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right)^2 + 
-0.036639124*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right)^2 + \\
&-0.002739534*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + 
-0.076610337*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + 
0.003781266*\left(\frac{(annWetDegDays\_WEATH - 0.02989113)}{0.243425185}\right)^2 + \\
&0.133413710*\left(\frac{(precip\_CLIM- 613.900118155)}{502.187690606}*\frac{(annWetDegDays\_CLIM - 1762.977520092)}{1160.20756048}\right) + \\
&-0.106746867*\left(\frac{(annWetDegDays\_CLIM - 1762.977520092)}{1160.20756048}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + 
0.125888447*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)\big\} - 2
\end{array}
$$

AKA: 
BareGroundCover~ exp( 2.746284299 +  0.262457983\*((tmean_CLIM- 10.275203571) / 4.912309147) +  0.087718972\*((isothermality_CLIM - 38.120111845) / 5.019479015) + -0.715375616\*((annWetDegDays_CLIM - 1762.977520092) / 1160.20756048) + -0.267155829\*((coarse - 12.799273363) / 11.332548324) + -0.064084039\*((isothermality_WEATH - 0.538807833) / 1.422356333)  + 0.037782133\*((annWetDegDays_WEATH - 0.02989113) / 0.243425185) + -0.079708661\*I(((tmean_CLIM- 10.275203571) / 4.912309147)^2) + -0.036639124\*I(((isothermality_CLIM- 38.120111845) / 5.019479015)^2) + -0.002739534\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) + -0.076610337\*((precip_CLIM - 613.900118155) / 502.187690606) + 0.003781266\*I(((annWetDegDays_WEATH - 0.02989113) / 0.243425185)^2) +  0.133413710\*(((precip_CLIM - 613.900118155) / 502.187690606)\*((annWetDegDays_CLIM - 1762.977520092) / 1160.20756048)) + -0.106746867\*(((annWetDegDays_CLIM - 1762.977520092) / 1160.20756048)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) +  0.125888447\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268))) - 2

## "Level 2" functional group cover models
### The proportion of total herbaceous that is C3 grass -- CONUS-wide 
$$
\begin{array}{cl}
&C3grassCoverPercentage \sim~ exp\big\{3.904167492 + -0.284822539*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} + -0.387430439*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268} + \\
&-0.264775838*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} + -0.168662971*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right)^2 + \\
&-0.294089719*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} + 
-0.009509765*\frac{(annWetDegDays\_CLIM - 1762.977500000)}{1160.207600000}\big\} - 2
\end{array}
$$

AKA: 
c3 cover percentage ~ exp( 3.904167492 + -0.284822539\*((tmean_CLIM- 10.275203571) / 4.912309147) + -0.387430439\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268) + -0.264775838\*((isothermality_CLIM- 38.120111845) / 5.019479015) + -0.168662971\*I(((isothermality_CLIM- 38.120111845) / 5.019479015)^2) + -0.294089719\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) + -0.009509765\*((annWetDegDays_CLIM- 1762.977500000)/1160.207600000)) - 2

### The proportion of total herbaceous that is C4 grass -- CONUS-wide 
$$
\begin{array}{cl}
 &C4grassCoverPercentage \sim exp\big\{2.41145985 + 0.48381716*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} + 1.02026843*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268} + \\
& 0.54331054*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} + 0.05180567*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right)^2\big\} - 2
\end{array}
$$

AKA: 
c4 cover percentage~ exp(2.41145985 + 0.48381716\*((tmean_CLIM- 10.275203571) / 4.912309147) + 1.02026843\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268) + 0.54331054\*((isothermality_CLIM- 38.120111845) / 5.019479015) + 0.05180567\*I(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)^2)) - 2


### The proportion of total herbaceous that is forbs -- CONUS-wide 
$$
\begin{array}{cl}
&forbCoverPercentage \sim exp\big\{3.514178452 + 
0.248393795*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + 
-0.052267180*\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382} + \\
&-0.050423003*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268} + 
-0.020802257*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015} +  
0.041673226*\frac{(sand - 47.706485501)}{16.730875594} +  \\
&0.059813143*\frac{(coarse - 12.799273363)}{11.332548324} + 
-0.035820999*\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}  +  
0.051567741*\left(\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}\right)^2 + \\ 
&0.014241935*\left(\frac{(precipSeasonality\_WEATH - -0.025697534)}{0.132964252}\right)^2 +  
0.005274193*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right)^2 +\\
&-0.037700614*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(annWetDegDays\_CLIM - 1762.977500000)}{1160.207600000}\right) +  -0.041194253*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) + \\
&0.060107858*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) + 
-0.092114033*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(AWHC - 13.671423701)}{5.155757156}\right) + \\
&-0.053246622*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(coarse - 12.799273363)}{11.332548324}\right) + 0.022969730*\left(\frac{(precipSeasonality\_CLIM - 0.923249309)}{0.245954382}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right) + \\
&0.004823926*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}\right)^2 +  
0.011303772*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}*\frac{(annWetDegDays\_WEATH - 0.02989113)}{0.243425185}\right)\big\} - 2
\end{array}
$$

AKA\* 
forb cover percentage~ exp( 3.514178452 +  0.248393795\*((precip_CLIM - 613.900118155) / 502.187690606) + -0.052267180\*((precipSeasonality_CLIM - 0.923249309) / 0.245954382) + -0.050423003\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268) + -0.020802257\*((isothermality_CLIM- 38.120111845) / 5.019479015) +  0.041673226\*((sand - 47.706485501) / 16.730875594) +  0.059813143\*((coarse - 12.799273363) / 11.332548324) + -0.035820999\*((precipSeasonality_WEATH - -0.025697534) / 0.132964252)  +  0.051567741\*I(((precipSeasonality_CLIM - 0.923249309) / 0.245954382)^2) +  0.014241935\*I(((precipSeasonality_WEATH - -0.025697534) / 0.132964252) ^2) +  0.005274193\*I(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)^2) +-0.037700614\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((annWetDegDays_CLIM - 1762.977520092) / 1160.20756048)) + -0.041194253\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) +  0.060107858\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((tmean_CLIM- 10.275203571) / 4.912309147))+ -0.092114033\*(((sand - 47.706485501) / 16.730875594)\*((AWHC - 13.671423701) / 5.155757156)) + -0.053246622\*(((sand - 47.706485501) / 16.730875594)\*((coarse - 12.799273363) / 11.332548324)) +  0.022969730\*(((precipSeasonality_CLIM - 0.923249309) / 0.245954382)\*((tmean_CLIM- 10.275203571) / 4.912309147)) +  0.004823926\*I(((isothermality_WEATH - 0.538807833) / 1.422356333) ^2) +  0.011303772\*(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)\*((annWetDegDays_WEATH - 0.02989113) / 0.243425185))) - 2

### The proportion of total tree that is broad-leaved -- forest
$$
\begin{array}{cl}
&broadLeavedTreeCoverPercentage \sim exp\big\{ 3.400837432 +  
0.119928190*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} +  
0.254698982*\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958} + \\
&0.415003665*\frac{(clay - 18.489433548)}{9.078669938}) +  
0.005289910*\frac{(sand - 47.706485501)}{16.730875594} + 
-0.118297218*\frac{(carbon - 3.681945502)}{6.405262851} +  \\
&0.216869470*\frac{(AWHC - 13.671423701)}{5.155757156} + 
0.127567513*\frac{(precip\_WEATH - 0.030312573)}{0.168767355}  + 
-0.030975228*\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922} +\\
&-0.136571036*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + 
0.026270176*\left(\frac{(isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(isothermality\_WEATH- 0.538807833)}{1.422356333}\right)  + 
-0.218615897*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&-0.013504372*\left(\frac{(isothermality\_WEATH - 0.538807833)}{1.422356333}*\frac{(precip\_CLIM- 613.900118155)}{502.187690606}\right)  + 
-0.079997868*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precip\_WEATH - 0.030312573)}{0.168767355}\right)  + \\
&-0.001941377*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + 
-0.108094550*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + \\
&0.056873963*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_WEATH -0.012171065)}{0.139613922}\right) + 
-0.084394634*\left(\frac{(carbon - 3.681945502)}{6.405262851}*\frac{(AWHC - 13.671423701)}{5.155757156}\right) + \\
&-0.011095426*\left(\frac{(carbon - 3.681945502)}{6.405262851}*\frac{(coarse - 12.799273363)}{11.332548324}\right) +  
0.126127030*\left(\frac{(clay - 18.489433548)}{9.078669938})*\frac{(coarse - 12.799273363)}{11.332548324}\right) + \\
&-0.249606357*\left(\frac{(sand - 47.706485501)}{16.730875594}*\frac{(coarse - 12.799273363)}{11.332548324}\right)\big\} - 2
\end{array}
$$
AKA: 
broadLeavedTree cover percentage~ exp( 3.400837432 +  0.119928190\*((tmean_CLIM- 10.275203571) / 4.912309147) +  0.254698982\*((precipDry_CLIM - 5.000260635) / 8.205443958) +  0.415003665\*((clay - 18.489433548) / 9.078669938) +  0.005289910\*((sand - 47.706485501) / 16.730875594) + -0.118297218\*((carbon - 3.681945502) / 6.405262851) +  0.216869470\*((AWHC - 13.671423701) / 5.155757156) +  0.127567513\*((precip_WEATH - 0.030312573) / 0.168767355)  + -0.030975228\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922) + -0.136571036\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) +  0.026270176\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((isothermality_WEATH - 0.538807833) / 1.422356333))  + -0.218615897\*(((isothermality_CLIM- 38.120111845) / 5.019479015)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.013504372\*(((isothermality_WEATH - 0.538807833) / 1.422356333) \*((precip_CLIM - 613.900118155) / 502.187690606)) + -0.079997868\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precip_WEATH - 0.030312573) / 0.168767355))  + -0.001941377\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.108094550\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) +  0.056873963\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)) + -0.084394634\*(((carbon - 3.681945502) / 6.405262851)\*((AWHC - 13.671423701) / 5.155757156)) + -0.011095426\*(((carbon - 3.681945502) / 6.405262851)\*((coarse - 12.799273363) / 11.332548324)) +  0.126127030\*(((clay - 18.489433548) / 9.078669938)\*((coarse - 12.799273363) / 11.332548324)) + -0.249606357\*(((sand - 47.706485501) / 16.730875594)\*((coarse - 12.799273363) / 11.332548324))) - 2

### The proportion of total tree that is needle-leaved -- forest
$$
\begin{array}{cl}
&needleLeavedTreeCoverPercentage\sim exp\big\{ 4.37205983 + 
-0.21286237*\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958} +  
0.12039825*\frac{(sand - 47.706485501)}{16.730875594} + \\
&0.07954909*\frac{(carbon - 3.681945502)}{6.405262851} + 
0.03631508*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right)^2 +  
0.06724832*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) +\\
&-0.08652516*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right) + -0.04245934*\left(\frac{(precipDry\_CLIM - 5.000260635)}{8.205443958}*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}\right)\big\} - 2
\end{array}
$$

AKA: 
needleLeavedTree cover percentage~ exp( 4.37205983 + -0.21286237\*((precipDry_CLIM - 5.000260635) / 8.205443958) + 0.12039825\*((sand - 47.706485501) / 16.730875594) +  0.07954909\*((carbon - 3.681945502) / 6.405262851) +  0.03631508\*I(((tmean_CLIM- 10.275203571) / 4.912309147)^2) + 0.06724832\*(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) + -0.08652516\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268)) + -0.04245934\*(((precipDry_CLIM - 5.000260635) / 8.205443958)\*((tmean_CLIM- 10.275203571) / 4.912309147))) - 2

### The proportion of total tree that is broad-leaved -- non-forest
$$
\begin{array}{cl}
&broadLeavedTreeCoverPercentage\sim exp\big\{ 3.10338252 +  
0.28241315*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} +  
0.80500002*\frac{(precip\_CLIM- 613.900118155)}{502.187690606} + \\
&0.05186862*\frac{(AWHC - 13.671423701)}{5.155757156} + 
-0.03647871*\left(\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)^2 + 
-0.06790977*\left(\frac{(precipTempCorr\_WEATH - 0.012171065)}{0.139613922}\right)^2 + \\
&0.18569895*\left(\frac{(sand - 47.706485501)}{16.730875594}\right)^2 +  
0.52842267*\left(frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) + \\
&-0.30139958*\left(\frac{(AWHC - 13.671423701)}{5.155757156}*\frac{(coarse - 12.799273363)}{11.332548324}\right)\big\} - 2
\end{array}
$$

AKA\* 
broadLeavedTree cover percentage~ exp( 3.10338252 + 0.28241315\*((tmean_CLIM- 10.275203571) / 4.912309147) +  0.80500002\*((precip_CLIM - 613.900118155) / 502.187690606) + 0.05186862\*((AWHC - 13.671423701) / 5.155757156) + -0.03647871\*I(((precipTempCorr_CLIM - -0.120988193) / 0.410662268)^2) + -0.06790977\*I(((precipTempCorr\_WEATH - 0.012171065) / 0.139613922)^2) +  0.18569895\*I(((sand - 47.706485501) / 16.730875594)^2) +  0.52842267\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) + -0.30139958\*(((AWHC - 13.671423701) / 5.155757156)\*((coarse - 12.799273363) / 11.332548324))) - 2
 
### The proportion of total tree that is needle-leaved -- non-forest
$$
\begin{array}{cl}
&needleLeavedTreeCoverPercentage\sim exp\big\{ 4.52324174 + 
-0.18954119*\frac{(tmean\_CLIM - 10.275203571)}{4.912309147} + 
-0.13086877*\frac{(AWHC - 13.671423701)}{5.155757156} + \\
&-0.03177446*\left(\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right)^2 + 
-0.25163832*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(annWatDef\_CLIM- 99.631248729)}{85.941823498}\right) + \\
&-0.24377773*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(Isothermality\_CLIM- 38.120111845)}{5.019479015}\right) + -0.32422844*\left(\frac{(tmean\_CLIM - 10.275203571)}{4.912309147}*\frac{(precipTempCorr\_CLIM- -0.120988193)}{0.410662268}\right)\big\} - 2
\end{array}
$$
AKA: 
needleLeavedTree cover percentage~ exp( 4.52324174 + -0.18954119\*((tmean_CLIM- 10.275203571) / 4.912309147) + -0.13086877\*((AWHC - 13.671423701) / 5.155757156) + -0.03177446\*I(((isothermality_CLIM- 38.120111845) / 5.019479015)^2) + -0.25163832\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((annWatDef_CLIM - 99.631248729) / 85.941823498)) + -0.24377773\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((isothermality_CLIM- 38.120111845) / 5.019479015)) + -0.32422844\*(((tmean_CLIM- 10.275203571) / 4.912309147)\*((precipTempCorr_CLIM - -0.120988193) / 0.410662268))) - 2

# Scale predictions of level 2 cover variables so each grouping sums to 100

## For components of total herbaceous cover

###
*Scaled C3 grass percentage* $= \frac{ eqn. 2.3.1}{(eqn. 2.3.1 + eqn. 2.3.2 + eqn. 2.3.3)}$

###
*Scaled C4 grass percentage* $= \frac{ eqn. 2.3.2}{(eqn. 2.3.1 + eqn. 2.3.2 + eqn. 2.3.3)}$

###
*Scaled forb grass percentage* $= \frac{ eqn. 2.3.3}{(eqn. 2.3.1 + eqn. 2.3.2 + eqn. 2.3.3)}$

## For components of total tree cover -- forest

###
*Scaled broad-leaved tree percentage* $= \frac{ eqn. 2.3.4}{(eqn. 2.3.4 + eqn. 2.3.5)}$

###
*Scaled needle-leaved tree percentage* $= \frac{ eqn. 2.3.5}{(eqn. 2.3.4 + eqn. 2.3.5)}$

## For components of total tree cover -- non-forest

###
*Scaled broad-leaved tree percentage* $= \frac{ eqn. 2.3.6}{(eqn. 2.3.6 + eqn. 2.3.7)}$

###
*Scaled needle-leaved tree percentage* $= \frac{ eqn. 2.3.7}{(eqn. 2.3.6 + eqn. 2.3.7)}$

# Where relevant, "relativize" the model predictions according to predicted ecoregion percentage

## Level 1-- Total Tree Cover 
*Relativized total tree cover* $= (eqn. 2.2.4 * eqn.2.1) + (eqn. 2.2.3 * (1-eqn.2.1))$

## Level 1-- Total Herbaceous Cover
*Relativized total herbaceous cover* $= (eqn. 2.2.2 * eqn.2.1) + (eqn. 2.2.1 * (1-eqn.2.1))$

## Level 2-- Broad-leaved tree percentage
*Relativized and scaled broad-leaved tree percentage* $= (eqn. 3.2.1 * eqn.2.1) + (eqn.3.3.1 * (1-eqn.2.1))$

## Level 2-- Needle-leaved tree percentage
*Relativized and scaled needle-leaved tree percentage* $= (eqn. 3.2.2 * eqn.2.1) + (eqn.3.3.2 * (1-eqn.2.1))$

# Scale relativized predictions of level 1 cover variables to sum to 100, **resulting in final predictions of level 1 cover variables**
## 
*final Total Herbaceous Cover* $= \frac{ eqn. 4.2}{(eqn. 4.2 + eqn. 4.1 + eqn. 2.2.5 + eqn. 2.2.6)}$

##
*final Total Tree Cover* $= \frac{ eqn. 4.1}{(eqn. 4.2 + eqn. 4.1 + eqn. 2.2.5 + eqn. 2.2.6)}$

##
*final Shrub Cover* $= \frac{ eqn. 2.2.5}{(eqn. 4.2 + eqn. 4.1 + eqn. 2.2.5 + eqn. 2.2.6)}$

##
*final Bare Ground Cover* $= \frac{ eqn. 2.2.6}{(eqn. 4.2 + eqn. 4.1 + eqn. 2.2.5 + eqn. 2.2.6)}$

# Multiply scaled (and relativized, where applicable) predictions of level 2 cover variables by scaled and relativized level 1 cover variable predictions,  **resulting in final predictions of level 2 cover variables**
## 
*final C4 grass cover* $= \frac{eqn.3.1.1}{100} * eqn. 5.1$

## 
*final C3 grass cover*$= \frac{eqn.3.1.2}{100} * eqn. 5.1$

## 
*final forb cover* $= \frac{eqn.3.1.3}{100} * eqn. 5.1$

## 
*final broad-leaved tree cover* $= \frac{eqn.4.3}{100} * eqn. 5.2$

## 
*final needle-leaved tree cover* $= \frac{eqn.4.4}{100} * eqn. 5.2$

